[workspace]
name = "Griddle"
root = "." # repo root

[tasks.Build]
desc = "Build"
cmd = ["dotnet", "build", "Griddle.slnx"] 
# cmd = ["dotnet", "run", "--project", "src/Griddle.App/Griddle.App.csproj"]


[tasks.Griddle]
desc = "Run Sparrow"
cmd = ["dotnet", "run", "--project", "src/Griddle.App/Griddle.App.csproj"]

# [tasks.dev]
# desc = "Run API (dev)"
# cmd = ["uvicorn", "app:app", "--reload", "--port", "8080"]

# [tasks.test]
# desc = "Run tests"
# cmd = ["pytest", "-q"]

# [tasks.web]
# desc = "Run frontend (if you have one)"
# cwd = "frontend"
# cmd = ["npm", "run", "dev"]