<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
  </ItemGroup>

  <Target
    Name="BuildMacOSCaptureBridge"
    BeforeTargets="Build"
    Condition="$([System.OperatingSystem]::IsMacOS())">

    <Exec
      Command="clang -fobjc-arc -fblocks -dynamiclib -framework AppKit -framework ScreenCaptureKit -o &quot;$(OutputPath)libGriddleCaptureBridge.dylib&quot; &quot;$(MSBuildProjectDirectory)/MacOS/Native/GriddleCaptureBridge.m&quot;" />

  </Target>

  <Target
    Name="BuildMacOSRecordingBridge"
    BeforeTargets="Build"
    Condition="$([System.OperatingSystem]::IsMacOS())">

    <Exec
      Command="clang -fobjc-arc -fblocks -dynamiclib -framework AppKit -framework ScreenCaptureKit -framework CoreMedia -framework AVFoundation -o &quot;$(OutputPath)libGriddleRecordingBridge.dylib&quot; &quot;$(MSBuildProjectDirectory)/MacOS/Native/GriddleRecordingBridge.m&quot;" />

  </Target>

</Project>